version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: &web-volumes
      - &app-volume .:/task_manager
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - &bundle-cache-volume bundle_cache:/bundle_cache
      - &node-volume node_modules:/task_manager/node_modules
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    depends_on:
      - db
      - redis
      - sidekiq
    environment: &web-environment
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache
      GEM_PATH: /bundle_cache
      RAILS_PORT: 3000
      RUBYOPT: -W:no-deprecated -W:no-experimental
      REDIS_URL: redis://redis
    command: bash -c "bundle exec rails s -b '0.0.0.0' -p 3000"

  webpacker:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "yarn && ./bin/webpack-dev-server"
    ports:
      - 3035:3035
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes: *web-volumes

  db:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:5.0.9-alpine

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "bundle exec sidekiq -C /task_manager/config/sidekiq.yml"
    environment: *web-environment
    volumes: *web-volumes
    depends_on:
      - redis

volumes:
  bundle_cache:
  node_modules: